# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn reserve
        env:
          NC_EMAIL: ${{ secrets.NC_EMAIL }}
          NC_PASSWORD: ${{ secrets.NC_PASSWORD }}
          RESERVE_TEACHER_IDS: ${{ secrets.RESERVE_TEACHER_IDS }}
      - name: Archive screenshots
        uses: actions/upload-artifact@v1
        with:
          name: screenshots
          path: screenshots
