# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          apt-get update
          apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont --no-install-recommends
          rm -rf /var/lib/apt/lists/*
          rm -rf /src/*.deb
      - run: yarn install
      - run: yarn reserve
        env:
          NC_EMAIL: ${{ secrets.NC_EMAIL }}
          NC_PASSWORD: ${{ secrets.NC_PASSWORD }}
          RESERVE_TEACHER_IDS: ${{ secrets.RESERVE_TEACHER_IDS }}
          CI: true
      - name: Archive screenshots
        uses: actions/upload-artifact@v1
        with:
          name: screenshots
          path: screenshots
